name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/YTLitePlus/YTLitePlus.git
          git fetch upstream
          git merge upstream/main --allow-unrelated-histories
          git push origin main
